# Drawing Conclusions Using Groupby

Use `winequality_edited.csv`. You should've created this data file in the previous section: *Appending Data (cont.)*.

In [1]:
# Load dataset
import pandas as pd

df =pd.read_csv('winequality_edited.csv')

### Is a certain type of wine associated with higher quality?

In [6]:
# Find the mean quality of each wine type (red and white) with groupby
df.groupby('color').mean()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
color,,,,,,,,,,,,
red,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
white,6.854788,0.278241,0.334192,6.391415,0.045772,35.308085,138.360657,0.994027,3.188267,0.489847,10.514267,5.877909

### What level of acidity receives the highest average rating?

In [8]:
# View the min, 25%, 50%, 75%, max pH values with Pandas describe
df.pH.describe()

count    6497.000000
mean        3.218501
std         0.160787
min         2.720000
25%         3.110000
50%         3.210000
75%         3.320000
max         4.010000
Name: pH, dtype: float64

In [9]:
# Bin edges that will be used to "cut" the data into groups
bin_edges = [2.72 ,3.11,3.21,3.32 ,4.01 ] # Fill in this list with five values you just found

In [11]:
# Labels for the four acidity level groups
bin_names = ['High','Moderatly High','Medium','Low' ] # Name each acidity level category

In [12]:
# Creates acidity_levels column
df['acidity_levels'] = pd.cut(df['pH'], bin_edges, labels=bin_names)

# Checks for successful creation of this column
df.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,color,acidity_levels
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,Low
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red,Moderatly High
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red,Medium
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red,Moderatly High
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red,Low

In [14]:
# Find the mean quality of each acidity level with groupby
df.groupby('acidity_levels').mean()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
acidity_levels,,,,,,,,,,,,
High,7.543914,0.294683,0.370792,7.088876,0.055131,33.179965,129.897496,0.994708,3.029062,0.503937,10.330208,5.783343
Moderatly High,7.365064,0.318551,0.340548,5.931984,0.054666,33.229154,126.815886,0.994697,3.164833,0.509300,10.391073,5.784540
Medium,7.143566,0.346751,0.313585,4.721159,0.055715,28.983995,111.182138,0.994476,3.267010,0.541287,10.610369,5.850832
Low,6.769949,0.403815,0.243901,3.848983,0.058777,26.327510,93.244917,0.994899,3.433348,0.574136,10.656057,5.859593

In [15]:
# Save changes for the next section
df.to_csv('winequality_edited.csv', index=False)